name: Restrict Edits to anwser.txt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  restrict:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check modified files
        run: |
          echo "Checking changed files..."
          base_ref="${{ github.event.before }}"
          head_ref="${{ github.sha }}"

          # Get changed files
          files=$(git diff --name-only "$base_ref" "$head_ref" || true)
          echo "Changed files:"
          echo "$files"

          # Allow only anwser.txt
          disallowed=$(echo "$files" | grep -v '^anwser.txt$' || true)

          if [ -n "$disallowed" ]; then
            echo "❌ You changed files other than anwser.txt:"
            echo "$disallowed"
            echo "This push is not allowed."
            exit 1
          else
            echo "✅ Only anwser.txt was modified. Push allowed."
          fi
