name: Restrict Edits to anwser.txt

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full history so we can diff properly

      - name: Verify only anwser.txt was edited
        run: |
          echo "🔍 Checking changed files..."

          # Determine diff base depending on event
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            BASE_SHA="${{ github.event.pull_request.base.sha }}"
            HEAD_SHA="${{ github.event.pull_request.head.sha }}"
          else
            BASE_SHA="${{ github.event.before }}"
            HEAD_SHA="${{ github.sha }}"
          fi

          CHANGED=$(git diff --name-only "$BASE_SHA" "$HEAD_SHA")
          echo "Changed files:"
          echo "$CHANGED"

          # Allow only anwser.txt
          FORBIDDEN=$(echo "$CHANGED" | grep -v '^anwser\.txt$' || true)

          if [ -n "$FORBIDDEN" ]; then
            echo "❌ The following files are not allowed to be modified:"
            echo "$FORBIDDEN"
            exit 1
          fi

          if [ -z "$CHANGED" ]; then
            echo "⚠️ No file changes detected — nothing to check."
            exit 0
          fi

          echo "✅ Only anwser.txt was modified — allowed."
          echo "✅ Only anwser.txt was modified — allowed."
